
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

homeassistant:
  external_url: "https://rdwnet.duckdns.org:8123"
  internal_url: "http://192.168.4.54:8123"  # Replace with your Home Assistant server's local IP
  time_zone: "America/Detroit"
  unit_system: imperial